services:
  php:
    build: ./
    ports: 
      - 8001:80
    depends_on:
      - pgsql
    links:
      - pgsql

  
  pgsql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $DB2_PASS
      POSTGRES_DB: $DB2_NAME
      POSTGRES_USER: $DB2_USER
    volumes:
      - ./database3:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql


  pgadmin:
    image: dockage/phppgadmin:latest
    ports:
      - 8121:80
    environment:
#     PMA_ARBITRARY: 1
      PHP_PG_ADMIN_SERVER_HOST: pgsql
      PGADMIN_DEFAULT_EMAIL: $DB2_USER
      PGADMIN_DEFAULT_PASSWORD: $DB2_PASS

volumes:
  mabase:
